# Clase 2 - Arreglos y Funciones

Los arreglos (Arrays) son una colección ordenada de elementos. Dentro de los arreglos se encuentran las listas, vectores, tablas y matrices

In [1]:
a=[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

Julia informa que se ha creado un arreglo de 3 elementos, dimensión 1, y typeof()= Int64

In [20]:
b=[0,1.9,2,3] #observar que Julia "homogeiniza" el typeof

4-element Array{Float64,1}:
 0.0
 1.9
 2.0
 3.0

In [6]:
s=["hola", "que tal"]

2-element Array{ASCIIString,1}:
 "hola"   
 "que tal"

In [7]:
f=[sin, cos, tan]

3-element Array{Function,1}:
 sin
 cos
 tan

In [8]:
tan(2)

-2.185039863261519

In [11]:
t=[1,"a",sin, pi, e]

5-element Array{Any,1}:
  1                    
   "a"                 
   sin                 
 π = 3.1415926535897...
 e = 2.7182818284590...

In [19]:
typeof(t)

Array{Any,1}

In [13]:
x=Float64[1,2,3] # Podemos definir el tipo de un arreglo

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [16]:
Int64[1.0,5]

2-element Array{Int64,1}:
 1
 5

In [1]:
Int64[1.1,6] # cuando tiene sentido

LoadError: LoadError: InexactError()
while loading In[1], in expression starting on line 1

##Arreglos 2dimensionales y matrices
Si no usamos comas, entonces el arreglo se convierte en un arreglo 2dimensional

In [22]:
v=[1 2 3] #matriz 1x2

1x3 Array{Int64,2}:
 1  2  3

In [23]:
A=[1 2 3 ; 5 6 7] # agregando ; se agrega nueva fila

2x3 Array{Int64,2}:
 1  2  3
 5  6  7

In [24]:
[1 2 3 , 4 5 6] # no funciona con ,

LoadError: LoadError: syntax: unexpected comma in matrix expression
while loading In[24], in expression starting on line 1

###Vectores columna y fila
Si escribimos un arreglo sin comas, puede ser pensado como un vector fila, y con comas como un vector columna

In [31]:
v=[1 2 3] # observar la dimensión =1

1x3 Array{Int64,2}:
 1  2  3

In [32]:
w=[3;4;5] # observar la dimensión =2

3-element Array{Int64,1}:
 3
 4
 5

In [34]:
u=[3,4,5]

3-element Array{Int64,1}:
 3
 4
 5

In [39]:
Vector(3) # alias de arreglo 1dim

3-element Array{Any,1}:
 #undef
 #undef
 #undef

In [40]:
Matrix(2,3) # alias de arreglo matricial

2x3 Array{Any,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [6]:
A=Array{Int,2}(2,3)

2x3 Array{Int64,2}:
 12884901891  0  140592958395568
  2147483649  0                0

##Accediendo al contenido

In [17]:
A=[(1,1) (1,2) (1,3) ; (2,1) (2,2) (2,3)]

2x3 Array{Tuple{Int64,Int64},2}:
 (1,1)  (1,2)  (1,3)
 (2,1)  (2,2)  (2,3)

In [7]:
a=(1,2) # tuple

(1,2)

In [9]:
a[1]=2

LoadError: LoadError: MethodError: `setindex!` has no method matching setindex!(::Tuple{Int64,Int64}, ::Int64, ::Int64)
while loading In[9], in expression starting on line 1

In [16]:
A[1]="a"

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Tuple{Int64,Int64}}, ::ASCIIString)
This may have arisen from a call to the constructor Tuple{Int64,Int64}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T<:Tuple{Any,Vararg{Any}}}, !Matched::T<:Tuple{Any,Vararg{Any}})
  convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T<:Tuple{Any,Vararg{Any}}}, !Matched::Tuple{Any,Vararg{Any}})
  ...
while loading In[16], in expression starting on line 1

In [18]:
A

2x3 Array{Tuple{Int64,Int64},2}:
 (1,1)  (1,2)  (1,3)
 (2,1)  (2,2)  (2,3)

In [51]:
for i in 1:6
    println(A[i])
end

(1,1)
(2,1)
(1,2)
(2,2)
(1,3)
(2,3)


In [52]:
A[1,2]

(1,2)

In [53]:
A[end]

(2,3)

In [20]:
v=[1 2 3 4 5 6 7 8 9]

1x9 Array{Int64,2}:
 1  2  3  4  5  6  7  8  9

In [25]:
v=v+v

1x9 Array{Int64,2}:
 2  4  6  8  10  12  14  16  18

In [26]:
v[2:6]

5-element Array{Int64,1}:
  4
  6
  8
 10
 12

In [61]:
A

2x3 Array{Tuple{Int64,Int64},2}:
 (1,1)  (1,2)  (1,3)
 (2,1)  (2,2)  (2,3)

In [65]:
A[2,3]=(100,100)

(100,100)

In [66]:
A

2x3 Array{Tuple{Int64,Int64},2}:
 (1,1)  (1,2)  (1,3)    
 (2,1)  (2,2)  (100,100)

In [68]:
A[2,3]= 1.9 # no acepta el cambio de typeof()

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Tuple{Int64,Int64}}, ::Float64)
This may have arisen from a call to the constructor Tuple{Int64,Int64}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T<:Tuple{Any,Vararg{Any}}}, !Matched::T<:Tuple{Any,Vararg{Any}})
  convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T<:Tuple{Any,Vararg{Any}}}, !Matched::Tuple{Any,Vararg{Any}})
  ...
while loading In[68], in expression starting on line 1

In [79]:
A=Array{Any,2}(2,3) #creando matriz 2x3 de tipo cualquiera

2x3 Array{Any,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [74]:
for i in [1,2]
    for j in [1,2,3]
    A[i,j]=(i,j)
    end
end

In [75]:
A

2x3 Array{Any,2}:
 (1,1)  (1,2)  (1,3)
 (2,1)  (2,2)  (2,3)

In [76]:
A[2,3]="chau"

"chau"

In [77]:
A

2x3 Array{Any,2}:
 (1,1)  (1,2)  (1,3) 
 (2,1)  (2,2)  "chau"

In [33]:
v=[1,2]

2-element Array{Int64,1}:
 1
 2

In [38]:
v

"hola"

In [34]:
w="hola"

"hola"

In [36]:
v=w

"hola"

In [39]:
w="chau"

"chau"

LoadError: LoadError: unsupported or misplaced expression :=
while loading In[41], in expression starting on line 1

## Arreglos y rangos de numéros
###Operador :, range(), y collect()

In [86]:
a=1:10 #esto no es un arreglo, pero define un rango de números

1:10

In [84]:
typeof(a)

UnitRange{Int64}

In [88]:
 for n in 1:10 print(n) end

12345678910

In [95]:
for n in 1.5:3.5 println(n) end #se puede definir rangos decimales

1.5
2.5
3.5


In [43]:
for n in 1.5:3.3 println(n) end

1.5
2.5


In [94]:
for n in 1.5:10 println(n) end

1.5
2.5
3.5
4.5
5.5
6.5
7.5
8.5
9.5


In [87]:
range(1,10) # mismo que antes pero sólo para Int y no para float

1:10

In [44]:
range(1.5,3.5)

LoadError: LoadError: MethodError: `range` has no method matching range(::Float64, ::Float64)
Closest candidates are:
  range(::AbstractFloat, ::AbstractFloat, !Matched::Integer)
  range(::Real, ::AbstractFloat, !Matched::Integer)
  range(::AbstractFloat, ::Real, !Matched::Integer)
  ...
while loading In[44], in expression starting on line 1

In [90]:
collect(1:10) #collect() sirve para crear un array de un rango

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [45]:
collect(1:5)==[1,2,3,4,5]

true

In [47]:
collect(0:0.25:1.22) #también definimos tamaño 

5-element Array{Float64,1}:
 0.0 
 0.25
 0.5 
 0.75
 1.0 

In [48]:
collect(1:2:10)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

###Rangos definidos
Funciones linspace(), step()

In [49]:
a=linspace(0,1,4) # construye un rango entre 0 y 1 en 4 "puntos"

linspace(0.0,1.0,4)

In [50]:
collect(a)

4-element Array{Float64,1}:
 0.0     
 0.333333
 0.666667
 1.0     

In [125]:
step(a)# nos dice el tamaño del paso

0.3333333333333333

In [126]:
step(linspace(0,10,5))

2.5

In [53]:
?linspace

search: linspace LinSpace InlineDisplay



```
linspace(start, stop, n=100)
```

Construct a range of `n` linearly spaced elements from `start` to `stop`.


## Creación de arreglos

### Por comprensión

In [127]:
[n^2 for n in 1:5]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [129]:
[(i,j) for i in 1:5, j in [1,3]]

5x2 Array{Tuple{Int64,Int64},2}:
 (1,1)  (1,3)
 (2,1)  (2,3)
 (3,1)  (3,3)
 (4,1)  (4,3)
 (5,1)  (5,3)

###Específicas
####zeros(), ones(), rand(), trues(), falses(), eye(), diagm(), fill()

In [145]:
zeros(5) # crea vector de ceros

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [131]:
zeros(2,3) #crea matriz de ceros

2x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [133]:
ones(2,3) #crea matriz de ceros

2x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [134]:
ones(Int64,2,3) #crea matriz de ceros

2x3 Array{Int64,2}:
 1  1  1
 1  1  1

In [136]:
eye(3, 3) # matriz identidad

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [137]:
eye(Int,3, 3)

3x3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

In [139]:
diagm(1:6) #matriz diagonal

6x6 Array{Int64,2}:
 1  0  0  0  0  0
 0  2  0  0  0  0
 0  0  3  0  0  0
 0  0  0  4  0  0
 0  0  0  0  5  0
 0  0  0  0  0  6

In [140]:
diagm([1, 2,3.0])

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  2.0  0.0
 0.0  0.0  3.0

In [36]:
x=rand(5) #el comando rand() nos da un vector columna (arreglo 1dim) random

5-element Array{Float64,1}:
 0.819638 
 0.594405 
 0.737785 
 0.0877251
 0.937554 

In [55]:
?randn

search: randn randn! sprandn randstring rand! rand randexp randperm randjump



```
randn([rng], [dims...])
```

Generate a normally-distributed random number with mean 0 and standard deviation 1. Optionally generate an array of normally-distributed random numbers.


In [38]:
X=rand(2,3) # matriz 2x3 al azar

2x3 Array{Float64,2}:
 0.454722  0.0345542  0.753601
 0.057494  0.2485     0.408083

In [56]:
trues(3, 4)

3x4 BitArray{2}:
 true  true  true  true
 true  true  true  true
 true  true  true  true

In [57]:
falses(4,5)

4x5 BitArray{2}:
 false  false  false  false  false
 false  false  false  false  false
 false  false  false  false  false
 false  false  false  false  false

In [147]:
fill(1.3, 9) # llena de 1.3 un array de 9 elementos

9-element Array{Float64,1}:
 1.3
 1.3
 1.3
 1.3
 1.3
 1.3
 1.3
 1.3
 1.3

In [148]:
fill("hola", 2, 2)

2x2 Array{ASCIIString,2}:
 "hola"  "hola"
 "hola"  "hola"

In [60]:
a = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [59]:
fill(0,5)==zeros(Int,5)

true

In [154]:
fill!(a, 1) # fill!() sirve para cambiar un array ya establecido

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [157]:
A=Array{Any}(2,2,3) #matriz 2x2x3

2x2x3 Array{Any,3}:
[:, :, 1] =
 #undef  #undef
 #undef  #undef

[:, :, 2] =
 #undef  #undef
 #undef  #undef

[:, :, 3] =
 #undef  #undef
 #undef  #undef

In [159]:
fill!(A,1)

2x2x3 Array{Any,3}:
[:, :, 1] =
 1  1
 1  1

[:, :, 2] =
 1  1
 1  1

[:, :, 3] =
 1  1
 1  1

###Localizando items en arrays
#### in, find(), findin(), filter()

In [76]:
a=1:10

1:10

In [77]:
4 in a

true

In [78]:
4 in [1,2,3,4]

true

In [79]:
x=collect(a)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [81]:
x

10-element Array{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [68]:
isinteger(2.0) # funciona que retorna true si es  o coincide con entero

true

In [69]:
iseven(2) # funciona que retorna true si el entero es par

true

In [73]:
colador=find(iseven,x) #retorna los arreglo de indices donde función retorna true

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [74]:
find(isodd,x)

0-element Array{Int64,1}

In [85]:
x==10

false

In [87]:
find((x->true),x)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [90]:
find((t->t==4),x)

1-element Array{Int64,1}:
 2

In [92]:
findin(["a",2,3,4],[1,"a",8]) #=retorna array con índices donde elementos de
primer entrada están en segundo array=#

1-element Array{Int64,1}:
 1

In [201]:
filter(isodd,1:10)# se queda con los elemento que pasan test (i.e. true)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

##Características de Arreglos
#### ndims(), size(), length(),countnz()

In [94]:
a=[1,2,3]; A=rand(2,2); AA=rand(2,3,4);

In [95]:
size(AA) # tuple de dimensiones

(2,3,4)

In [96]:
ndims(AA)

3

In [97]:
length(A)

4

In [196]:
size(AA)

(2,3,4)

In [191]:
length(A)

4

In [192]:
ndims(A)

2

In [193]:
ndims(a)

1

In [199]:
countnz([1 2 3 4; 5 0 0 0]) #cuenta entradas no cero

5

##Operaciones sobre arreglos

### Operacions globales
#### sum(), mean(), prod(), combinations(), permutations()

In [98]:
a=[1,2,3,4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [204]:
sum(a)

10

In [212]:
println(sum(a)), println(prod(a)), println(mean(a))

10
24
2.5


(nothing,nothing,nothing)

In [99]:
combinations(a,2)# encuentra todas los posibles combinaciones de 2 eltos

Base.Combinations{Array{Int64,1}}([1,2,3,4],2)

In [100]:
collect(ans)

6-element Array{Array{Int64,1},1}:
 [1,2]
 [1,3]
 [1,4]
 [2,3]
 [2,4]
 [3,4]

In [101]:
collect(combinations(a,1))

4-element Array{Array{Int64,1},1}:
 [1]
 [2]
 [3]
 [4]

In [102]:
collect(combinations(a,3))

4-element Array{Array{Int64,1},1}:
 [1,2,3]
 [1,2,4]
 [1,3,4]
 [2,3,4]

In [223]:
collect(permutations(a))#todas las permutaciones

24-element Array{Array{Int64,1},1}:
 [1,2,3,4]
 [1,2,4,3]
 [1,3,2,4]
 [1,3,4,2]
 [1,4,2,3]
 [1,4,3,2]
 [2,1,3,4]
 [2,1,4,3]
 [2,3,1,4]
 [2,3,4,1]
 [2,4,1,3]
 [2,4,3,1]
 [3,1,2,4]
 [3,1,4,2]
 [3,2,1,4]
 [3,2,4,1]
 [3,4,1,2]
 [3,4,2,1]
 [4,1,2,3]
 [4,1,3,2]
 [4,2,1,3]
 [4,2,3,1]
 [4,3,1,2]
 [4,3,2,1]

###Modificando arreglos
#### push!(), unshift!(),  splice!(), pop!(), deleteat!() ....

In [111]:
a = collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [112]:
push!(a,11)# agrega al final

11-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11

In [113]:
pop!(a) #elimina último

11

In [114]:
unshift!(a,0)#agrega al principio

11-element Array{Int64,1}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [115]:
shift!(a) #elimina al ppio

0

In [116]:
a

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [117]:
#splice!(collection, index, [replacement]) -> item
a=collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [118]:
splice!(a,1,19)

1

In [119]:
a

10-element Array{Int64,1}:
 19
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [120]:
b=[10,20,40,50]

4-element Array{Int64,1}:
 10
 20
 40
 50

In [123]:
splice!(b,2:4,[1,2, 3,4,5,6,6,7,7])

3-element Array{Int64,1}:
 20
 30
 40

In [124]:
b

10-element Array{Int64,1}:
 10
  1
  2
  3
  4
  5
  6
  6
  7
  7

In [125]:
a=[-2,-1,0,1,2,3,4]

7-element Array{Int64,1}:
 -2
 -1
  0
  1
  2
  3
  4

In [126]:
splice!(a,1:3)

3-element Array{Int64,1}:
 -2
 -1
  0

In [127]:
a

4-element Array{Int64,1}:
 1
 2
 3
 4

In [275]:
a=[1:3;]

3-element Array{Int64,1}:
 1
 2
 3

In [285]:
B=[1:3]

3-element Array{Int64,1}:
 1
 2
 3

In [286]:
push!(B,4)

4-element Array{Int64,1}:
 1
 2
 3
 4

##EJEMPLOS

In [297]:
B=[1 2 ; 3 4]

2x2 Array{Int64,2}:
 1  2
 3  4

In [299]:
A=B.==2

2x2 BitArray{2}:
 false   true
 false  false

In [300]:
B[A]

1-element Array{Int64,1}:
 2

In [4]:

#Dado un vector, verificar si es una permutacion:
function isPermutation(A::AbstractArray{Int,1})
    N=maximum(A)
    Res = true
    if length(A)==N
      Res =false
    end
    for entry in A
      #we can select the subvector of entries matching a given criterion
      println(length(A[A.==entry]))
      if length(A[A.==entry])!=1
        Res = false
      end
    end
    return Res
end
#Una mejor idea es chequear que todos tengan tamaño a lo mas N
# y que la suma sea el numero correcto (N+1)*N/2

function unPaso(Lista, N)
  Res = []
  for perm in Lista
    #print("Ahora aca $perm")
    #println(typeof(perm))
    for indice in indicesValidos(perm, N)
      #print("Estoy aca $indice")
      temp = copy(perm)
      push!(temp, indice)
      push!(Res, temp)
    end
  end
  print(Res)
  return Res
end

function indicesValidos(perm, N)
  return filter((x)-> !(x in perm),[1:N;])
end

#Algo importante aca es como inicializar un arreglo de arreglos, es una de las cosas inesperadas de Julia.
N=3
Res = unPaso(Array{Int64}[[]],N)
Res = unPaso(Res,N)

function permutacionLenta(N)
  Res = Array{Int64}[[]]
  for k in 1:N
    Res = unPaso(Res,N)
  end
  return Res
end

S = permutacionLenta(4)
length(S) == factorial(4)

Any[[1],[2],[3]]Any[[1,2],[1,3],[2,1],[2,3],[3,1],[3,2]]Any[[1],[2],[3],[4]]Any[[1,2],[1,3],[1,4],[2,1],[2,3],[2,4],[3,1],[3,2],[3,4],[4,1],[4,2],[4,3]]Any[[1,2,3],[1,2,4],[1,3,2],[1,3,4],[1,4,2],[1,4,3],[2,1,3],[2,1,4],[2,3,1],[2,3,4],[2,4,1],[2,4,3],[3,1,2],[3,1,4],[3,2,1],[3,2,4],[3,4,1],[3,4,2],[4,1,2],[4,1,3],[4,2,1],[4,2,3],[4,3,1],[4,3,2]]Any[[1,2,3,4],[1,2,4,3],[1,3,2,4],[1,3,4,2],[1,4,2,3],[1,4,3,2],[2,1,3,4],[2,1,4,3],[2,3,1,4],[2,3,4,1],[2,4,1,3],[2,4,3,1],[3,1,2,4],[3,1,4,2],[3,2,1,4],[3,2,4,1],[3,4,1,2],[3,4,2,1],[4,1,2,3],[4,1,3,2],[4,2,1,3],[4,2,3,1],[4,3,1,2],[4,3,2,1]]

true

In [5]:
isPermutation([1,2,3,4])

1
1
1
1


false