Tuples -  (sucesiones inmutables)

In [1]:
x=(1,2,3)

(1,2,3)

In [2]:
x[1]==1

true

In [3]:
x[1:3]

(1,2,3)

In [4]:
typeof(x)

Tuple{Int64,Int64,Int64}

In [5]:
a,b=x

(1,2,3)

In [6]:
b

2

In [7]:
a

1

In [8]:
println("$a,$b")

1,2


ARRAYS -  son secuencias mutables 

In [9]:
[1,2] # vector columna

2-element Array{Int64,1}:
 1
 2

In [10]:
[1 2] # matriz  1x2

1x2 Array{Int64,2}:
 1  2

In [29]:
[1;2]==[1,2]

true

In [11]:
zeros(4) # vector con ceros 

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [12]:
ones(3,2)

3x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [13]:
ones(Int64,3,2)

3x2 Array{Int64,2}:
 1  1
 1  1
 1  1

In [14]:
ones(Bool,3,2)

3x2 Array{Bool,2}:
 true  true
 true  true
 true  true

In [15]:
trues(3,2)

3x2 BitArray{2}:
 true  true
 true  true
 true  true

In [16]:
falses(2,3)

2x3 BitArray{2}:
 false  false  false
 false  false  false

In [17]:
eye(4)

4x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [18]:
x=linspace(0,1,5) #partición equidistribuída en 5 partes de [0,1]

linspace(0.0,1.0,5)

In [19]:
collect(x) # da un array con los elementos de linspace

5-element Array{Float64,1}:
 0.0 
 0.25
 0.5 
 0.75
 1.0 

In [20]:
1:10

1:10

In [21]:
collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [22]:
x=[10,20]

2-element Array{Int64,1}:
 10
 20

In [23]:
resize!(x,5) #cambia tamaño y agrega basura

5-element Array{Int64,1}:
     10
     20
 569348
      1
      1

In [24]:
collect((1,2,3)) #convierte tuple en array

3-element Array{Int64,1}:
 1
 2
 3

In [25]:
[x*y for x in 1:3, y in [1,2,3]] # matriz 2 x 2

3x3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

In [26]:
v=[1,0,0]


3-element Array{Int64,1}:
 1
 0
 0

In [27]:
[1 2 3; 4 5 6]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6